version: "3.7"
services:
  redis:
    image: redis:5.0.4-alpine

  mongodb:
    image: mongo

  scheme-adapter:
    image: ${REPO}/sdk-scheme-adapter:${VER}
    build:
      context: ../sdk-scheme-adapter
    env_file: ./config/scheme-adapter.lewbank1.env
    volumes:
      - ../sdk-scheme-adapter/package.json:/opt/sdk-scheme-adapter/package.json
      - ../sdk-scheme-adapter/src:/opt/sdk-scheme-adapter/src
    depends_on:
      - redis
    command:
      - npm run docker-dev
  
  sheet-fsp:
    image: ${REPO}/sheet-fsp:${VER}
    build:
      context: .
    volumes:
      - ./package.json:/opt/sheet-fsp/package.json
      - ./tsconfig.json:/opt/sheet-fsp/tsconfig.json
      - ./config:/opt/sheet-fsp/config
      - ./src:/opt/sheet-fsp/src
      - ./node_modules:/opt/sheet-fsp/node_modules
    depends_on:
      - scheme-adapter
      - mongodb
    command:
      - npm run watch
      # - npm run watch-ts-node
      # - "tail -f /dev/null"
