displayName: |
  SMS Endpoints
description: |
  Send sms messages
/sms:
  post:
    description: |
      send an sms message to the given number
    body:
      application/json:
        type: Foo
        example: { "id" : 5, "name" : "Another foo" }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "ok": "OK"
             }
    securedBy: [none]

types:
  foo: |
    { "$schema": "http://json-schema.org/schema",
       "type": "object",
       "description": "Foo details",
       "properties": {
         "id": { "type": integer },
         "name": { "type": "string" },
         "ownerName": { "type": "string" }
       },
       "required": [ "id", "name" ]
    }
